repos:
-   repo: https://github.com/pycqa/flake8
    rev: '7.3.0'
    hooks:
    -   id: flake8
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: "v21.1.0"
    hooks:
    -   id: clang-format
        types_or:
            - "c"
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.17.1'
    hooks:
    -   id: mypy
